name: Test and generate

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  test:
    name: Go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: |
          go test ./...
  generate:
    name: Ensure generate ran before push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Generate
        run: |
          go generate ./...
          git diff --exit-code
